# Generated by Django 4.0.4 on 2023-03-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("PostId", models.AutoField(primary_key=True, serialize=False)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("Description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserApp.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostImages",
            fields=[
                ("PostImageId", models.AutoField(primary_key=True, serialize=False)),
                ("Image", models.ImageField(upload_to="")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="PostApp.posts",
                    ),
                ),
            ],
        ),
    ]
