# Generated by Django 4.0.4 on 2023-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PostApp", "0002_alter_postimages_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimages",
            name="Image",
            field=models.ImageField(upload_to="Media/"),
        ),
    ]
