# Generated by Django 4.0.4 on 2023-04-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PostApp", "0003_alter_postimages_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimages",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="postimages",
            old_name="PostImageId",
            new_name="post_image_id",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="CreatedAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="PostId",
            new_name="post_id",
        ),
    ]
