# Generated by Django 4.0.4 on 2023-04-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_users_avatar'),
        ('PostApp', '0004_rename_image_postimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to='UserApp.users'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='UserApp.users'),
        ),
    ]
