repos:
  -   repo: local
      hooks:
          - id: mypy
            name: mypy
            entry: mypy
            language: system
            types: [ python ]
            args: ["--ignore-missing-imports", "--scripts-are-modules", "--disable-error-code", "attr-defined"]
            exclude:  '^.*/migrations/.*$'
          - id: flake8
            name: flake8
            entry: python -m flake8
            language: system
            types: [ python ]
          - id: isort
            name: isort
            entry: python -m isort
            language: system
            types: [ python ]
          - id: black
            name: black
            entry: python -m black
            language: system
            types: [ python ]