# Generated by Django 4.0.4 on 2023-04-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_rename_avatar_users_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                default="Media/profile_images/default_avatar.png",
                upload_to="profile_images",
            ),
        ),
    ]
