# Generated by Django 4.0.4 on 2023-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("UserId", models.AutoField(primary_key=True, serialize=False)),
                ("Password", models.CharField(max_length=500)),
                ("Email", models.EmailField(max_length=254)),
                ("IsRegistered", models.BooleanField()),
                ("Username", models.CharField(max_length=500)),
                (
                    "Avatar",
                    models.ImageField(
                        default="profile_images/default_avatar.png",
                        upload_to="profile_images",
                    ),
                ),
                ("Biography", models.TextField()),
            ],
        ),
    ]
