# Generated by Django 4.0.4 on 2023-04-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0003_alter_users_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="IsRegistered",
            field=models.BooleanField(default=False),
        ),
    ]
