# Generated by Django 4.0.4 on 2023-04-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0004_alter_users_isregistered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="Avatar",
            new_name="avatar",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="Biography",
            new_name="biography",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="IsRegistered",
            new_name="is_registered",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="Password",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="UserId",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="Username",
            new_name="username",
        ),
    ]
