# Generated by Django 4.0.4 on 2023-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimages",
            name="Image",
            field=models.TextField(),
        ),
    ]
